# Название нашего workflow. Оно будет отображаться в разделе "Actions" на GitHub
name: Docker Image CI

# Триггер: Условие, при котором workflow будет запускаться
on:
  # Запускать при каждом push в ветку main
  push:
    branches: [ "main" ]

# Задачи (Jobs): Список задач, которые нужно выполнить
jobs:
  # Мы определили одну задачу и назвали ее 'build'
  build:
    # Указываем, на какой операционной системе будет работать наша задача.
    # GitHub предоставит нам "виртуальную машину" с последней версией Ubuntu.
    runs-on: ubuntu-latest

    # Шаги (Steps): Последовательность действий, которые нужно выполнить в рамках задачи
    steps:
      # Шаг 1: Клонирование репозитория
      # Это стандартное действие, которое скачивает ваш код на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Сборка Docker-образа
      # Мы используем готовое действие от сообщества Docker для упрощения сборки
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          # 'context' указывает, где находится Dockerfile ('.' - в корне проекта)
          context: .
          # 'push: false' означает, что мы только собираем образ, но не отправляем его никуда
          push: false
          # 'tags' задает имя для нашего образа. Пока это просто для примера.
          tags: my-docker-image:latest