# .github/workflows/docker-build.yml

name: Build, Push and Deploy to K8s

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Install Yandex.Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "/home/runner/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Create Service Account key file
        run: |
          cat <<EOF > sa-key.json
          ${{ secrets.YC_SA_KEY_FOR_K8S }}
          EOF

      - name: Authenticate in Yandex.Cloud
        # Теперь мы берем ID из секретов, а не вставляем в код
        run: |
          yc config set service-account-key sa-key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Get K8s cluster credentials
        run: yc managed-kubernetes cluster get-credentials --name my-dev-cluster --external

      - name: Replace image tag in deployment manifest
        run: sed -i 's|IMAGE_TAG|${{ github.sha }}|' deployment.yml

      - name: Deploy to Kubernetes
        run: kubectl apply -f .```
**Что изменилось:**
*   Мы убрали ваши ID из кода.
*   Теперь `yc config set ...` берет значения из секретов `${{ secrets.YC_CLOUD_ID }}` и `${{ secrets.YC_FOLDER_ID }}