# Название нашего workflow
name: Docker Image CI/CD

# Триггер: Запускать при пуше в main
on:
  push:
    branches: [ "main" ]

# Задачи (Jobs)
jobs:
  build-and-push: # Мы переименовали задачу для ясности
    runs-on: ubuntu-latest
    # Добавляем права на запись в Packages
    permissions:
      contents: read
      packages: write

    # Шаги (Steps)
    steps:
      # Шаг 1: Клонирование репозитория (остался без изменений)
      - name: Checkout repository
        uses: actions/checkout@v4

      # НОВЫЙ ШАГ 2: Вход в GitHub Container Registry
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN - это временный секретный ключ, который GitHub Actions создает автоматически
          # для авторизации в рамках репозитория.
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ИЗМЕНЕННЫЙ ШАГ 3: Сборка и Публикация Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # 'push: true' - теперь мы отправляем образ
          push: true
          # 'tags' - мы задаем правильное имя для образа в GHCR
          # Формат: ghcr.io/ВАШ_НИКНЕЙМ/ИМЯ_РЕПОЗИТОРИЯ:latest
          tags: ghcr.io/${{ github.repository }}:latest