name: Build, Push and Deploy to K8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Шаг 1: Сборка и публикация образа (немного изменен) ---
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Создаем два тега: latest и уникальный по хэшу коммита
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      # --- Шаг 2: Развертывание в Yandex Cloud K8s ---
      - name: Install Yandex.Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "/home/runner/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate in Yandex.Cloud
        run: |
          echo '${{ secrets.YC_SA_KEY_FOR_K8S }}' > sa-key.json
          yc config set service-account-key sa-key.json
          yc config set cloud-id <b1gq2skmnrhbocitkhi8> # <-- ЗАМЕНИТЕ
          yc config set folder-id <b1g10ltn901u7m511qi2> # <-- ЗАМЕНИТЕ

      - name: Get K8s cluster credentials
        run: yc managed-kubernetes cluster get-credentials --name my-dev-cluster --external

      - name: Replace image tag in deployment manifest
        run: sed -i 's|IMAGE_TAG|${{ github.sha }}|' deployment.yml

      - name: Deploy to Kubernetes
        run: kubectl apply -f .